### ISSUE TITLE
How to add a torrent file to the Web UI?

### ISSUE THREAD

**Issue by saki-osive** [emmercm/docker-qbittorrent#101]
Hi, I can download torrents using Magnet links, however, how do I download a torrent with a .torrent file using the Web UI, as I do by clicking on it or opening it with the app for the Desktop app?

**Comment by zilexa** [comment]
Your browser needs to know where to send the link. So you need to fix that in your browser. 
Easiest is to use an addon. For example for Firefox: https://addons.mozilla.org/nl/firefox/addon/torrent-control/

**Comment by emmercm** [comment]
With the qBittorrent web UI you upload the `.torrent` file - there's an icon in the toolbar that looks like a document with a plus sign.
